// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFbjMUVS0vh1KdYfiB2B3Tfo8YaPtjRuY',
    appId: '1:1082210299848:web:50b87dccc6150c0f375afd',
    messagingSenderId: '1082210299848',
    projectId: 'chatapp-8a3d1',
    authDomain: 'chatapp-8a3d1.firebaseapp.com',
    databaseURL: 'https://chatapp-8a3d1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8a3d1.firebasestorage.app',
    measurementId: 'G-DDE4R4DY1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDda2duWqSTYuzbX84DfW3F59XfiJ4ZkkA',
    appId: '1:1082210299848:android:d0f0281f659afafb375afd',
    messagingSenderId: '1082210299848',
    projectId: 'chatapp-8a3d1',
    databaseURL: 'https://chatapp-8a3d1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8a3d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwDPOXIwxDqcwqPCxqpdlwP-pjj0axyU',
    appId: '1:1082210299848:ios:994d798f140e621d375afd',
    messagingSenderId: '1082210299848',
    projectId: 'chatapp-8a3d1',
    databaseURL: 'https://chatapp-8a3d1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8a3d1.firebasestorage.app',
    iosBundleId: 'com.example.simplyserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANwDPOXIwxDqcwqPCxqpdlwP-pjj0axyU',
    appId: '1:1082210299848:ios:994d798f140e621d375afd',
    messagingSenderId: '1082210299848',
    projectId: 'chatapp-8a3d1',
    databaseURL: 'https://chatapp-8a3d1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8a3d1.firebasestorage.app',
    iosBundleId: 'com.example.simplyserve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFbjMUVS0vh1KdYfiB2B3Tfo8YaPtjRuY',
    appId: '1:1082210299848:web:63b01ecc42c34ea8375afd',
    messagingSenderId: '1082210299848',
    projectId: 'chatapp-8a3d1',
    authDomain: 'chatapp-8a3d1.firebaseapp.com',
    databaseURL: 'https://chatapp-8a3d1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-8a3d1.firebasestorage.app',
    measurementId: 'G-277FSJ5Y05',
  );
}
