name: simplyserve
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image:
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  motion_tab_bar:
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  mapbox_maps_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  
  http: ^1.6.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc:

  # Launcher Icons
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# -------------------------
# Launcher Icon Configuration
# -------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"  
